### ISSUE TITLE
GUI sizes incorrect on Windows 10

### ISSUE THREAD

**Issue by r4dian** [HertzDevil/SnevenTracker#11]
The icons and songinfo font are tiny, and the graph elements in the instrument editor are not aligned correctly:

SnevenTracker 0.2.2:
![a - sneven](https://cloud.githubusercontent.com/assets/1264174/22709176/caf60a16-ed70-11e6-91a9-995608fb5674.png)

0CC-Famitracker
![b - 0cc-ft](https://cloud.githubusercontent.com/assets/1264174/22709175/caeb4f68-ed70-11e6-83e5-d8b1141536ca.png)

Famitracker
![c - vanilla-ft](https://cloud.githubusercontent.com/assets/1264174/22709174/caea2656-ed70-11e6-977c-0525bb173657.png)

**Comment by HertzDevil** [comment]
DPI scaling is ported from 0.5.0 beta, therefore this will be disabled here
