### ISSUE TITLE
Possible Konami SCC expansion chip support?

### ISSUE THREAD

**Issue by ScoopJohn** [HertzDevil/SnevenTracker#4]
This expansion chip is most likely the N163 of SN7. It adds 5 channels which contain customizable waveforms. A difference between this and the N163 is that it has a larger height for waveforms. Since there will be KSS export support, i might issue this thing here.

**Comment by Xyz39808** [comment]
KSS with SCC is meant for MSX targets. All of which use the AY-3-8910 and not the SN76489. Would have to implement AY support beforehand but at least another Z80 machine and MSX OPLL support would be already done by then.
