### ISSUE TITLE
Feature Request: NDx command.

### ISSUE THREAD

**Issue by B00daW** [HertzDevil/SnevenTracker#8]
Almost as a desired effect, it would be nice if the noise channel disregards frequency input from supplied channels so that all 4 channels may have independent frequencies.

ND0 = Do not disregard frequency input from NCx channel.
ND1 = Disregard frequency input from all channels.

**Comment by HertzDevil** [comment]
this is literally a feature of T6W28, it will be configurable as a chip but definitely not a pattern effect
